### ISSUE TITLE
Suggestions and Errors in SD method

### ISSUE THREAD

**Issue by volutail** [thu-coai/LAUG#2]
1. the new span ignores the `candidate`
https://github.com/thu-coai/LAUG/blob/06033be36f7cb27b6c3f5e10adb9680374b2ce54/LAUG/aug/Speech_Disfluency/Speech_Disfluency.py#L87
2. the new `candidate` should be different from the original slot value, but in the SD augmented data:
`... on the south sorry , south side of town`

**Comment by hualai-liujiexi** [comment]
We have removed the original span from candidate:
`if span in candidate:    candidate.remove(span)`
In your example, I think it might be because that "south" is different from "south side".
But actually, we(human) know that "south" and "south side" have the same meaning.  
It might be better to add some entity linking rules in the future.

**Comment by volutail** [comment]
> We have removed the original span from candidate:
> `if span in candidate: candidate.remove(span)`
> In your example, I think it might be because that "south" is different from "south side".
> But actually, we(human) know that "south" and "south side" have the same meaning.
> It might be better to add some entity linking rules in the future.

It does not work.
https://github.com/thu-coai/LAUG/blob/06033be36f7cb27b6c3f5e10adb9680374b2ce54/LAUG/aug/Speech_Disfluency/Speech_Disfluency.py#L84
This condition is always `False`:
- The `candidate` is a `List` composed of `Str`
- The `span` is a `List`

**Comment by hualai-liujiexi** [comment]
Thanks for your advice.
We've fixed it now:
`if value in candidate:     candidate.remove(value)`
